cursor                #ffffff
cursor_text_color     #000000

foreground            #FFFFFF
background            #292929
selection_foreground  #000000
selection_background  #FFFFFF
url_color             #ff3333

# black
color0   #1a1a1a
color8   #404040

# red (Crimson Accents)
color1   #990000
color2   #8a1919
color10  #c92a2a

# Yellows (Hints of Yellow/Gold)
color3   #cc8800
color11  #ffcc00

# Medium/Light Grays 
color4   #ffd865
color12  #e7cc00

# Oranges 
color5   #cc5200
color13  #ff7300

# Red-Oranges/Rust
color6   #b33c00
color9   #D96F00
color14  #ff4c00

# Light Grays / White (Foreground/Text)
color7   #b3b3b3
color15  #e6e6e6
